### ISSUE TITLE
Installing SDK fails on test cases

### ISSUE THREAD

**Issue by JoranBergfeld** [Ingenico-ePayments/connect-sdk-java#3]
Trying to run a mvn clean install, resulting in a test case error:

Tests run: 12, Failures: 11, Errors: 0, Skipped: 0, Time elapsed: 0.278 sec <<< FAILURE! - in com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest

Can work around with a mvn clean install -Dmaven.test.skip=true.

**Comment by rob-spoor** [comment]
Does it also show why these tests fails? All but one of these tests fail, so there may be some issue with starting up the mock server.

**Comment by JoranBergfeld** [comment]
Hi Rob,

Entire stacktrace below:

testDeleteToken(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.03 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='a1c271d5-43cb-4a8b-92d2-36b53f7b9397'):
  method:       'DELETE'
  uri:          '/v1/1234/tokens/5678'
  headers:      'X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:11 GMT", Authorization="********", Host="localhost:62499", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'DELETE'
  uri:          '/v1/1234/tokens/5678'
  headers:      'X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:615)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testDeleteToken(DefaultConnectionLoggerTest.java:176)

testLoggingConvertAmount(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='76ff5624-4983-4108-8f3e-204dae81a60a'):
  method:       'GET'
  uri:          '/v1/1234/services/convert/amount?source=EUR&amount=1000&target=USD'
  headers:      'X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:11 GMT", Authorization="********", Host="localhost:62501", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'GET'
  uri:          '/v1/1234/services/convert/amount?source=EUR&amount=1000&target=USD'
  headers:      'X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:615)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testLoggingConvertAmount(DefaultConnectionLoggerTest.java:141)

testCreatePaymentRejected(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='125f55ea-dac5-4df5-bda6-e8f89c1b9619'):
  method:       'POST'
  uri:          '/v1/1234/payments'
  headers:      'Content-Type="application/json", X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:11 GMT", Authorization="********", Content-Length="244", Host="localhost:62503", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'
  content-type: 'application/json; charset=UTF-8'
  body:         '{"cardPaymentMethodSpecificInput":{"card":{"cvv":"***","cardNumber":"************3452","expiryDate":"**20"},"paymentProductId":1},"order":{"amountOfMoney":{"amount":2345,"currencyCode":"CAD"},"customer":{"billingAddress":{"countryCode":"CA"}}}}'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'POST'
  uri:          '/v1/1234/payments'
  headers:      'Content-Type="application/json", X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'
  content-type: 'application/json; charset=UTF-8'
  body:         '{"cardPaymentMethodSpecificInput":{"card":{"cvv":"***","cardNumber":"************3452","expiryDate":"**20"},"paymentProductId":1},"order":{"amountOfMoney":{"amount":2345,"currencyCode":"CAD"},"customer":{"billingAddress":{"countryCode":"CA"}}}}'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:615)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testCreatePaymentRejected(DefaultConnectionLoggerTest.java:382)

testCreatePayment(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.02 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='cfbb0c1f-78d8-4343-8123-cff234280ead'):
  method:       'POST'
  uri:          '/v1/1234/payments'
  headers:      'Content-Type="application/json", X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:11 GMT", Authorization="********", Content-Length="244", Host="localhost:62505", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'
  content-type: 'application/json; charset=UTF-8'
  body:         '{"cardPaymentMethodSpecificInput":{"card":{"cvv":"***","cardNumber":"************3456","expiryDate":"**20"},"paymentProductId":1},"order":{"amountOfMoney":{"amount":2345,"currencyCode":"CAD"},"customer":{"billingAddress":{"countryCode":"CA"}}}}'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'POST'
  uri:          '/v1/1234/payments'
  headers:      'Content-Type="application/json", X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'
  content-type: 'application/json; charset=UTF-8'
  body:         '{"cardPaymentMethodSpecificInput":{"card":{"cvv":"***","cardNumber":"************3456","expiryDate":"**20"},"paymentProductId":1},"order":{"amountOfMoney":{"amount":2345,"currencyCode":"CAD"},"customer":{"billingAddress":{"countryCode":"CA"}}}}'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:615)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testCreatePayment(DefaultConnectionLoggerTest.java:242)

testLogResponseOnly(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.02 sec  <<< FAILURE!
java.lang.AssertionError:
response message 'Incoming response (requestId='b09ad369-8057-40d4-aa04-ab2967ac3399', 3 ms):
  status-code:  '200'
  headers:      'Content-Type="application/json", Dummy="", Date="Wed, 30 Nov 2016 16:16:11 GMT", Server="TEST/1.1", Connection="Close"'
  content-type: 'application/json'
  body:         '{
    "result": "OK"
}'' does not match pattern \QIncoming response (requestId='\E([-a-zA-Z0-9]+)\Q', \E\d+\Q ms):
  status-code:  '200'
  headers:      'Content-Type="application/json", Dummy="", Date="\E[^"]+\Q"\E[^']*\Q'
  content-type: 'application/json'
  body:         '{
    "result": "OK"
}'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertResponse(DefaultConnectionLoggerTest.java:656)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertResponse(DefaultConnectionLoggerTest.java:647)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testLogResponseOnly(DefaultConnectionLoggerTest.java:572)

testLogRequestOnly(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.03 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='792cc9c6-7ecd-49e5-a53c-df4e58b0c038'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:12 GMT", Authorization="********", Host="localhost:62511", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testLogRequestOnly(DefaultConnectionLoggerTest.java:540)

testLoggingTestConnection(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='1c852332-4145-40a9-a3c5-31cfd13376ce'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:12 GMT", Authorization="********", Host="localhost:62513", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:615)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testLoggingTestConnection(DefaultConnectionLoggerTest.java:99)

testReadTimeout(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.028 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='9e7fd294-1842-4dea-bff5-17bb35646cac'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:12 GMT", Authorization="********", Host="localhost:62515", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndError(DefaultConnectionLoggerTest.java:627)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testReadTimeout(DefaultConnectionLoggerTest.java:505)

testCreatePaymentInvalidCardNumber(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='cb21f019-c7b5-48bc-9b77-cef3e7dac457'):
  method:       'POST'
  uri:          '/v1/1234/payments'
  headers:      'Content-Type="application/json", X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:12 GMT", Authorization="********", Content-Length="244", Host="localhost:62517", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'
  content-type: 'application/json; charset=UTF-8'
  body:         '{"cardPaymentMethodSpecificInput":{"card":{"cvv":"***","cardNumber":"************3456","expiryDate":"**20"},"paymentProductId":1},"order":{"amountOfMoney":{"amount":2345,"currencyCode":"CAD"},"customer":{"billingAddress":{"countryCode":"CA"}}}}'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'POST'
  uri:          '/v1/1234/payments'
  headers:      'Content-Type="application/json", X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'
  content-type: 'application/json; charset=UTF-8'
  body:         '{"cardPaymentMethodSpecificInput":{"card":{"cvv":"***","cardNumber":"************3456","expiryDate":"**20"},"paymentProductId":1},"order":{"amountOfMoney":{"amount":2345,"currencyCode":"CAD"},"customer":{"billingAddress":{"countryCode":"CA"}}}}'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:615)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testCreatePaymentInvalidCardNumber(DefaultConnectionLoggerTest.java:310)

testLoggingUnknownServerError(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='ab10c969-50c0-4426-93dd-5ffbabd321f8'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:12 GMT", Authorization="********", Host="localhost:62519", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testLoggingUnknownServerError(DefaultConnectionLoggerTest.java:423)

testNonJson(com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.AssertionError:
request message 'Outgoing request (requestId='cb5815cd-ac02-41fc-9611-f5156be8ef7a'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="eyJwbGF0Zm9ybUlkZW50aWZpZXIiOiJXaW5kb3dzIDcvNi4xIEphdmEvMS43IChPcmFjbGUgQ29ycG9yYXRpb247IEphdmEgSG90U3BvdChUTSkgNjQtQml0IFNlcnZlciBWTTsgMS43LjBfNzkpIiwic2RrSWRlbnRpZmllciI6IkphdmFTZXJ2ZXJTREsvdjUuMC4wIiwic2RrQ3JlYXRvciI6IkluZ2VuaWNvIiwiaW50ZWdyYXRvciI6IkluZ2VuaWNvIn0=", Date="Wed, 30 Nov 2016 16:16:12 GMT", Authorization="********", Host="localhost:62521", Connection="Keep-Alive", User-Agent="Apache-HttpClient/4.5.2 (Java/1.7.0_79)", Accept-Encoding="gzip,deflate"'' does not match pattern \QOutgoing request (requestId='\E([-a-zA-Z0-9]+)\Q'):
  method:       'GET'
  uri:          '/v1/1234/services/testconnection'
  headers:      'X-GCS-ServerMetaInfo="\E[^"]*\Q", Date="\E[^"]+\Q", Authorization="********"\E[^']*\Q'\E
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequest(DefaultConnectionLoggerTest.java:639)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.assertRequestAndResponse(DefaultConnectionLoggerTest.java:620)
        at com.ingenico.connect.gateway.sdk.java.defaultimpl.DefaultConnectionLoggerTest.testNonJson(DefaultConnectionLoggerTest.java:464)

**Comment by rob-spoor** [comment]
I think something has gone wrong in copy-pasting in this issue, because the number of asterisks is not correct. That appears to be caused by the GitHub formatting though, because if I copy-paste parts of your response, even more asterisks get removed. Could you verify that in your actual responses, there are 8 asterisks in the value for `Authorization`, and there is an asterisk after of the `[^"]` and `[^']` blocks?

I think this is caused by a line break inconsistency. The ZIP files contain files that use Linux line breaks. If you're using Windows then that will indeed cause these tests to fail.

**Comment by JoranBergfeld** [comment]
Ah yes. I tried to build on Windows. I resolved the issue by running mvn clean install -Dmaven.test.skip=true. :)

**Comment by rob-spoor** [comment]
A fix for this has been released yesterday, so no more need to skip tests.

**Comment by JoranBergfeld** [comment]
Thanks for the update.
